apiVersion: apps/v1
kind: Deployment
metadata:
  name: model-api
  labels:
    app: model-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: model-api
  template:
    metadata:
      labels:
        app: model-api
    spec:
      containers:
        - name: model-api
          image: ai-devacr.azurecr.io/model-api:v1
          ports:
            - containerPort: 5000
