# This GitHub Actions workflow builds a Docker image for the model API and deploys it to Azure Kubernetes Service (AKS).

name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

# env:
#   IMAGE_NAME: model-api
#   IMAGE_TAG: v1

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout repo
      #   uses: actions/checkout@v3

      # - name: Log in to Azure
      #   uses: azure/login@v1
      #   with:
      #     creds: ${{ secrets.AZURE_CREDENTIALS }}

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Build and push image to ACR
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: ./model-api
      #     push: true
      #     tags: ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      - name: Checkout repo
        uses: actions/checkout@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Build and push image to ACR
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: ./model-api
      #     push: true
      #     tags: ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
